apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-blog-mysql
  namespace: wp-blog
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql/mysql-server:8.0
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 3306
        envFrom:
          - configMapRef:
              name: wp-blog-config-map
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysqldb
      volumes:
        - name: mysqldb
          persistentVolumeClaim:
            claimName: wp-blog-mysql-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-blog-wordpress
  namespace: wp-blog
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        envFrom:
          - configMapRef:
              name: wp-blog-config-map
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-blog-wordpress-pvc
