apiVersion: v1
kind: Service
metadata:
  name: wp-blog-mysql
  namespace: wp-blog
  labels:
    app: mysql
spec:
  type: NodePort
  ports:
   - port: 3306
  selector:
   app: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: wp-blog-wordpress
  namespace: wp-blog
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
      nodePort: 30003
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
