apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wp-blog
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
      # nodePort: 31476
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: wp-pv-volume
  namespace: wp-blog
  labels:
    app: wordpress
spec:
  storageClassName: local
  capacity:
    storage: 500M
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/wordpress"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pvc-claim
  namespace: wp-blog
  labels:
    app: wordpress
spec:
  storageClassName: local
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wp-blog
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        envFrom:
          - configMapRef:
              name: postgres-config
        # env:
        # - name: WORDPRESS_DB_HOST
        #   value: wordpress-mysql
        # - name: WORDPRESS_DB_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: mysql-pass
        #       key: password
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pvc-claim
